apiVersion: apps/v1
kind: Deployment
metadata:
  name: odd-numbers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odd-numbers
  template:
    metadata:
      labels:
        app: odd-numbers
    spec:
      containers:
      - name: odd-numbers
        image: europe-docker.pkg.dev/ultimate-rig-438812-u4/registry/odd-app:0.04
        env:
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmqcluster-we1.rabbitmq.svc.cluster.local:5672"
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
